# Generated by Django 3.1.3 on 2020-11-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plateau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_length', models.IntegerField()),
                ('y_length', models.IntegerField()),
            ],
        ),
    ]
