# Generated by Django 3.1.3 on 2020-11-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_plateau'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plateau',
            old_name='y_length',
            new_name='y_height',
        ),
    ]
